// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivwrdyvipidukmgmrgme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2d3JkeXZpcGlkdWttZ21yZ21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MTE2NjIsImV4cCI6MjA1ODI4NzY2Mn0.4djFXc6pEKMeh2i49_4_2muro4ITqYoDNiWGkmD-yUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);